### ISSUE TITLE
There is no config.json file.

### ISSUE THREAD

**Issue by bavermelkor** [TiagoMarinho/Soph#31]
There is no config.json file. What can I do?

**Comment by TiagoMarinho** [comment]
Yes, this is by design. You're supposed to create it yourself. The `config.json` file is where your bot token resides, and as such it is a sensitive file. It's like the password of your bot.

Please see [the instructions in the readme file](https://github.com/TiagoMarinho/Soph#installation) regarding how to set up this file correctly.
