### ISSUE TITLE
"models.map is not a function" when running bot

### ISSUE THREAD

**Issue by astrotically** [TiagoMarinho/Soph#33]
I tried running the bot and it said this: 

Node.js v20.11.1
PS C:\Users\arief\OneDrive\Desktop\Soph\Soph> node .
(node:19360) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///C:/Users/arief/OneDrive/Desktop/Soph/Soph/src/shared/base-options.js:3
const modelChoices = models.map(m => ({
                            ^

TypeError: models.map is not a function
    at file:///C:/Users/arief/OneDrive/Desktop/Soph/Soph/src/shared/base-options.js:3:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.11.1

What should I do? Reply asap!

**Comment by TiagoMarinho** [comment]
I think this happens if you run Soph without the API being available (e.g. no webui running, or no --api commandline argument passed to the webui), but I have to check later to be sure. Just wanted to send this first so you know I'll look into it.

**Comment by TiagoMarinho** [comment]
after looking at this further, I find it quite odd. I remember doing something in the past that resulted in this but I don't recall exactly what I did
in all likelihood what's happening is that the variable `models` is being populated with something like `{ error: "something here" }` because the webui wasn't set up properly or whatever. I can't really reproduce it at this time, so maybe a solution would be to handle that case so it doesn't crash the bot at least

more information from the user regarding the exact steps they took to run the bot would be useful as well

**Comment by TiagoMarinho** [comment]
should be mitigated by 945c1b213e1d0f7414c6fb331e4ac92c0dd6a4d1
now the code should try to continue, and also logs unexpected responses to the console
if it keeps happening, please copy the logged response and paste it here, reopening the issue
